#!/bin/bash

get_record_info() {
    local subdomain=$1
    local domain=$2
    local record_type=$3

    dig_output=$(dig $subdomain.$domain | awk '/ANSWER SECTION:/ {flag=1; next} /;;/ {flag=0} flag')
    destination=$(echo "$dig_output" | awk -v type="$record_type" '$4 == type {print $5}')

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

main() {
    local domain=$1
    local subdomain=$2

    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi

    for sub in "${subdomains[@]}"; do
        case "$sub" in
            "www"|"lb-01")
                get_record_info "$sub" "$domain" "A"
                ;;
            "web-01"|"web-02")
                get_record_info "$sub" "$domain" "A"
                ;;
            *)
                echo "Unknown subdomain: $sub"
                ;;
        esac
    done
}
main "$@"
